name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read
  statuses: write
  checks: write
  pull-requests: write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build contracts (generates TypeChain types)
        run: pnpm exec nx build contracts

      - name: Copy TypeChain types before lint/typecheck
        run: pnpm exec nx copy-typechain-types contracts

      - name: Lint all projects
        run: pnpm exec nx run-many -t lint

      - name: Type check all projects
        run: pnpm exec nx run-many -t typecheck

      - name: Check Solidity formatting
        run: pnpm exec nx check-format-sol contracts

      - name: Smart contract tests
        run: pnpm exec nx test contracts

      - name: Frontend unit tests
        run: pnpm exec nx test frontend



  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
        
      - name: Setup virtual display for Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Start Hardhat network and wait for readiness
        run: |
          cd libs/contracts
          npx hardhat node &
          wait-on http://127.0.0.1:8545
        
      - name: Deploy contracts and copy artifacts  
        run: |
          cd libs/contracts
          npx hardhat ignition deploy ignition/modules/DeployAll.ts --network localhost
          cd ../..
          pnpm exec nx copy-artifacts contracts

      - name: Cache Synpress extension
        uses: actions/cache@v4
        id: synpress-cache
        with:
          path: apps/e2e/.cache-synpress
          key: ${{ runner.os }}-synpress-${{ hashFiles('apps/e2e/test/wallet-setup/basic.setup.ts') }}

      - name: Build Synpress cache
        if: steps.synpress-cache.outputs.cache-hit != 'true'
        env:
          DISPLAY: :99
        run: |
          cd apps/e2e
          npx synpress

      - name: Start frontend and wait for readiness
        run: |
          pnpm exec nx serve frontend &
          wait-on http://localhost:4200

      - name: Run e2e tests
        env:
          DISPLAY: :99
        run: |
          cd apps/e2e
          npx playwright test --config=playwright.config.ts

      - name: Upload screenshots to Argos
        if: always()
        run: |
          cd apps/e2e
          npx @argos-ci/cli upload ./screenshots
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/e2e/playwright-report/
          retention-days: 30