name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint all projects
        run: pnpm exec nx run-many -t lint

      - name: Type check all projects
        run: pnpm exec nx run-many -t typecheck

      - name: Check Solidity formatting
        run: pnpm exec nx check-format-sol contracts

      - name: Smart contract tests
        run: pnpm exec nx test contracts

  setup-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps


  e2e-tests:
    runs-on: ubuntu-latest
    needs: setup-e2e
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Restore Playwright browsers cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install wait-on
        run: npm install -g wait-on

      - name: Start Hardhat network and wait for readiness
        run: |
          cd libs/contracts
          npx hardhat node &
          wait-on http://127.0.0.1:8545
        
      - name: Deploy contracts and copy artifacts  
        run: |
          cd libs/contracts
          npx hardhat ignition deploy ignition/modules/DeployAll.ts --network localhost
          npm install -g ts-node
          cd ../..
          pnpm exec nx copy-artifacts contracts

      - name: Build Synpress cache
        run: |
          cd apps/frontend-e2e
          xvfb-run -a npx synpress

      - name: Run e2e tests
        run: |
          cd apps/frontend-e2e
          xvfb-run -a npx playwright test --config=synpress.config.ts