name: Deploy AMM dApp to Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: simple-amm
  REGION: us-central1
  REPOSITORY: simple-amm

jobs:
  deploy:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Configure Docker to use gcloud as credential helper
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Create Artifact Registry repository (if not exists)
      run: |
        gcloud artifacts repositories describe ${{ env.REPOSITORY }} \
          --location=${{ env.REGION }} || \
        gcloud artifacts repositories create ${{ env.REPOSITORY }} \
          --repository-format=docker \
          --location=${{ env.REGION }} \
          --description="Docker repository for simple-amm"

    - name: Build Container
      run: |-
        docker build \
          --build-arg VITE_TOKEN_ADDRESS="${{ secrets.VITE_TOKEN_ADDRESS }}" \
          --build-arg VITE_AMM_POOL_ADDRESS="${{ secrets.VITE_AMM_POOL_ADDRESS }}" \
          --build-arg VITE_NETWORK_CHAIN_ID="${{ secrets.VITE_NETWORK_CHAIN_ID }}" \
          -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./

    - name: Push Container
      if: github.ref == 'refs/heads/main'
      run: |-
        docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

    - name: Deploy to Cloud Run
      if: github.ref == 'refs/heads/main'
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
        env_vars: |
          VITE_TOKEN_ADDRESS=${{ secrets.VITE_TOKEN_ADDRESS }}
          VITE_AMM_POOL_ADDRESS=${{ secrets.VITE_AMM_POOL_ADDRESS }}
          VITE_NETWORK_CHAIN_ID=${{ secrets.VITE_NETWORK_CHAIN_ID }}

    - name: Show Output
      if: github.ref == 'refs/heads/main'
      run: echo ${{ steps.deploy.outputs.url }}